openapi: 3.0.0
info:
  title: InnerEcho API
  version: 1.0.0
  description: InnerEcho 챗봇 및 음성 처리 API 명세서

servers:
  - url: http://localhost:3001

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /user/register:
    post:
      summary: '사용자 회원가입'
      tags:
        - 'User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  example: '홍길동'
                user_email:
                  type: string
                  example: 'hong@example.com'
                password:
                  type: string
                  example: 'password1234'
                user_gender:
                  type: string
                  example: 'male'
      responses:
        '200':
          description: '회원가입 성공'
        '400':
          description: '이메일 또는 닉네임 중복'
        '500':
          description: '서버 오류'

  /user/login:
    post:
      summary: '사용자 로그인'
      tags:
        - 'User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
                  example: 'hong@example.com'
                password:
                  type: string
                  example: 'password1234'
      responses:
        '200':
          description: '로그인 성공 및 JWT 발급'
        '400':
          description: '이메일 또는 비밀번호가 틀림'
        '500':
          description: '서버 오류'

  /user/email:
    post:
      summary: '이메일 인증번호 발송'
      tags:
        - 'User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'hong@example.com'
      responses:
        '200':
          description: '인증번호 전송 성공'
        '500':
          description: '서버 오류'
          
  /user/emotion:
    post:
      summary: '사용자 감정 상태 조회'
      tags:
        - 'User'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                  example: 1
      responses:
        '200':
          description: '감정 상태(emotion) 반환'
        '404':
          description: '사용자를 찾을 수 없음'
        '500':
          description: '서버 오류'

  /user/token:
    get:
      summary: '토큰 검증'
      tags:
        - 'User'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: '토큰이 유효함'
        '401':
          description: '토큰이 유효하지 않음'
          
  /user/{user_id}:
    get:
      summary: '특정 사용자 정보 조회'
      tags:
        - 'User'
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
          description: 사용자 ID
      responses:
        '200':
          description: '사용자 정보 반환'
        '404':
          description: '사용자를 찾을 수 없음'
        '500':
          description: '서버 오류'
    put:
      summary: '사용자 정보 수정'
      tags:
        - 'User'
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
          description: 사용자 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: '수정된 사용자 정보 반환'
        '404':
          description: '사용자를 찾을 수 없음'
        '500':
          description: '서버 오류'
    delete:
      summary: '사용자 계정 삭제'
      tags:
        - 'User'
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
          description: 사용자 ID
      responses:
        '200':
          description: '계정 삭제 성공'
        '404':
          description: '사용자를 찾을 수 없음'
        '500':
          description: '서버 오류'

  /chat/plant:
    post:
      summary: 식물 챗봇과 대화
      tags:
        - 'Chat'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                  example: 1
                plant_id:
                  type: number
                  example: 1
                message:
                  type: string
                  example: '오늘 기분은 어때?'
      responses:
        '200':
          description: '챗봇 응답 성공'
        '500':
          description: '서버 오류'

  /chat/history:
    post:
      summary: 사용자-식물 대화 기록 조회
      tags:
        - 'Chat'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                  example: 1
                plant_id:
                  type: number
                  example: 1
      responses:
        '200':
          description: '대화 이력 조회 성공'
        '500':
          description: '서버 오류'
          
  /chat/emotion:
    post:
      summary: '채팅 시 사용자 감정 상태 저장'
      tags:
        - 'Chat'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                plant_id:
                  type: number
                message:
                  type: string
                emotion:
                  type: string
      responses:
        '200':
          description: '성공'
        '500':
          description: '서버 오류'

  /plant-state/{plant_id}:
    get:
      summary: '특정 식물의 현재 상태 조회'
      tags:
        - 'Plant State'
      parameters:
        - in: path
          name: plant_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: '식물 상태 정보 반환'
        '404':
          description: '식물을 찾을 수 없음'
        '500':
          description: '서버 오류'

  /plant-state/{plant_id}/experience:
    post:
      summary: '식물에게 경험치 부여'
      tags:
        - 'Plant State'
      parameters:
        - in: path
          name: plant_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                expGained:
                  type: number
      responses:
        '200':
          description: '변경된 식물 상태 반환'
        '500':
          description: '서버 오류'

  /plant-state/{plant_id}/likeability:
    post:
      summary: '식물의 호감도 증가'
      tags:
        - 'Plant State'
      parameters:
        - in: path
          name: plant_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
      responses:
        '200':
          description: '변경된 호감도 값 반환'
        '500':
          description: '서버 오류'
          
  /diary/month:
    post:
      summary: '월별 성장일기 작성일 조회'
      tags:
        - 'Diary'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                year_month:
                  type: string
                  example: '2025-07'
      responses:
        '200':
          description: '날짜 목록 반환'
        '400':
          description: '잘못된 파라미터'
        '500':
          description: '서버 오류'

  /diary/date:
    post:
      summary: 날짜별 성장일기 조회
      tags:
        - 'Diary'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                date:
                  type: string
                  example: '2025-07-21'
      responses:
        '200':
          description: '성장일기 조회 성공'
        '500':
          description: '서버 오류'

  /diary/create:
    post:
      summary: 성장일기 생성
      tags:
        - 'Diary'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                plant_id:
                  type: number
                message:
                  type: string
      responses:
        '200':
          description: '성장일기 생성 성공'
        '500':
          description: '서버 오류'

  /comment/list:
    post:
      summary: 성장일기 댓글 조회
      tags:
        - 'Comment'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                diary_id:
                  type: number
      responses:
        '200':
          description: '댓글 조회 성공'
        '500':
          description: '서버 오류'

  /comment/create:
    post:
      summary: 성장일기 댓글 생성
      tags:
        - 'Comment'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                diary_id:
                  type: number
                content:
                  type: string
      responses:
        '200':
          description: '댓글 생성 성공'
        '500':
          description: '서버 오류'
          
  /comment/update:
    post:
      summary: '성장일기 댓글 수정'
      tags:
        - 'Comment'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                diary_id:
                  type: number
                comment_id:
                  type: number
                content:
                  type: string
      responses:
        '200':
          description: '수정된 댓글 정보 반환'
        '500':
          description: '서버 오류'

  /comment/delete:
    post:
      summary: 성장일기 댓글 삭제
      tags:
        - 'Comment'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                diary_id:
                  type: number
                comment_id:
                  type: number
      responses:
        '200':
          description: '댓글 삭제 성공'
        '500':
          description: '서버 오류'

  /speech/stt:
    post:
      summary: 음성 파일을 텍스트로 변환 (STT)
      tags:
        - 'Speech'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: '변환된 텍스트 정보 반환'
        '400':
          description: '오디오 파일 없음'
        '500':
          description: '서버 오류'

  /speech/tts:
    post:
      summary: 텍스트를 음성으로 변환 (TTS)
      tags:
        - 'Speech'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: '음성 파일 (audio/ogg) 반환'
        '400':
          description: '메시지 없음'
        '500':
          description: 'TTS 오류'

  /mission/{user_id}:
    get:
      summary: '사용자의 미션 목록 조회'
      tags:
        - 'Mission'
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: '미션 목록 배열 반환'
        '500':
          description: '서버 오류'

  /mission/complete:
    post:
      summary: '미션 완료 처리'
      tags:
        - 'Mission'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                mission_id:
                  type: number
      responses:
        '200':
          description: '미션 완료 정보 반환'
        '500':
          description: '서버 오류'

  /mission/drinkwater:
    post:
      summary: "'물 마시기' 미션 완료"
      tags:
        - 'Mission'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                mission_id:
                  type: number
                missionImage:
                  type: string
                  format: binary
      responses:
        '200':
          description: '미션 완료 성공'
        '400':
          description: '필수 필드 누락'
        '500':
          description: '서버 오류'
          
  /mission/submitsmile:
    post:
      summary: "'웃는 사진 제출' 미션 완료"
      tags:
        - 'Mission'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                mission_id:
                  type: number
                smileImage:
                  type: string
                  format: binary
      responses:
        '200':
          description: '미션 완료 성공'
        '400':
          description: '필수 필드 누락'
        '500':
          description: '서버 오류'
          
  /mission/chatwithplant:
    post:
      summary: "'식물과 대화하기' 미션 완료"
      tags:
        - 'Mission'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                mission_id:
                  type: number
                plant_id:
                  type: number
                message:
                  type: string
      responses:
        '200':
          description: '채팅 및 미션 완료 정보 반환'
        '400':
          description: '필수 필드 누락'
        '500':
          description: '서버 오류'
          
  /mission/completestretching:
    post:
      summary: "'스트레칭 완료' 미션"
      tags:
        - 'Mission'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                mission_id:
                  type: number
      responses:
        '200':
          description: '스트레칭 미션 성공'
        '400':
          description: '필수 필드 누락'
        '500':
          description: '서버 오류'

  /friend/friendRequest:
    post:
      summary: '친구 요청 보내기'
      tags:
        - 'Friend'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
                friend_email:
                  type: string
      responses:
        '200':
          description: '친구 요청 성공'
        '400':
          description: '필수 필드 누락 또는 자기 자신에게 요청'
        '500':
          description: '서버 오류'
          
  /friend/requestAccept:
    post:
      summary: '친구 요청 수락'
      tags:
        - 'Friend'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
                friend_email:
                  type: string
      responses:
        '200':
          description: '친구 요청 수락 성공'
        '404':
          description: '친구 요청이 존재하지 않음'
        '500':
          description: '서버 오류'
          
  /friend/requestReject:
    post:
      summary: '친구 요청 거절'
      tags:
        - 'Friend'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
                friend_email:
                  type: string
      responses:
        '200':
          description: '친구 요청 거절 성공'
        '404':
          description: '친구 요청이 존재하지 않음'
        '500':
          description: '서버 오류'
          
  /friend/friendslist:
    get:
      summary: '친구 목록 조회'
      tags:
        - 'Friend'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: number
      responses:
        '200':
          description: '친구 이메일 목록 배열 반환'
        '404':
          description: '사용자를 찾을 수 없음'
        '500':
          description: '서버 오류'