# 워크플로우의 이름
name: Deploy Leafy Project

# 언제 이 워크플로우를 실행할지 정의
on:
  push:
    branches:
      - main  # main 브랜치에 push 이벤트가 발생했을 때 실행

# 실행될 작업(Job)들을 정의
jobs:
  # 첫 번째 Job: Docker 이미지 빌드 및 푸시
  build-and-push:
    runs-on: ubuntu-latest  # 이 Job을 실행할 가상 환경

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Docker 이미지 빌드 및 Docker Hub에 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Dockerfile이 있는 위치 (프로젝트 루트)
          push: true  # 빌드 후 푸시 실행
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/leafy:latest # 이미지 태그 설정 (예: myusername/leafy:latest)

  # 두 번째 Job: 서버에 배포
  deploy:
    needs: build-and-push  # build-and-push Job이 성공해야만 실행됨
    runs-on: ubuntu-latest

    steps:
      # 1. SSH를 통해 서버에 접속하여 배포 스크립트 실행
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/deploy
            mkdir -p leafy
            echo "${{ secrets.LEAFY_ENV }}" > ./leafy/.env
            docker compose pull leafy_api
            docker compose up -d --no-deps leafy_api